### ISSUE TITLE
官方是不再维护这个项目了么？

### ISSUE THREAD

**Issue by david1025** [CloudDeepTeam/amazeui#1007]
官方是不再维护这个项目了么？

**Comment by playermaker** [comment]
一年没更新了，看来死掉了

**Comment by chong0808** [comment]
还是比较喜欢这个ui的

**Comment by lwxyfer** [comment]
欢迎 PR。

**Comment by kinizumi** [comment]
全球12779颗星，居然就抛弃了，真丢人中国人的脸

**Comment by shenghanqin** [comment]
两耳不闻窗外事，一心只读圣贤书。

**Comment by weiyechaocat** [comment]
> 全球12779颗星，居然就抛弃了，真丢人中国人的脸

你是脑回路有问题吧？维护一个项目要多少精力，一直没有财力支持让你做你高兴？国内有个UI能做到1W多star很了不起了。还丢中国人的脸。

**Comment by zerogcl** [comment]
？？？？？？官方发邮件请把话说明白，你这种很容易让我误会是在说我，虽然我知道不是我，但是我的心里很不爽


------------------ 原始邮件 ------------------
发件人: "Noctis"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 中午11:28
收件人: "amazeui/amazeui"<amazeui@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [amazeui/amazeui] 官方是不再维护这个项目了么？ (#1007)



 
全球12779颗星，居然就抛弃了，真丢人中国人的脸
  
你是脑回路有问题吧？维护一个项目要多少精力，一直没有财力支持让你做你高兴？国内有个UI能做到1W多star很了不起了。还丢中国人的脸。
