### ISSUE TITLE
看来最终还是死掉了

### ISSUE THREAD

**Issue by playermaker** [CloudDeepTeam/amazeui#1012]
估计融资失败了吧

**Comment by xfworld** [comment]
不是融资失败，是实际上没有更好的应用场景了，目前是个人在维护

**Comment by walkfor** [comment]
3.0也一直没正式发布

**Comment by Akuns** [comment]
什么情况？

**Comment by anjia0532** [comment]
@xfworld 公司放弃了？为啥不考虑社区维护？

**Comment by piglingcn** [comment]
有没有别的Ui框架介绍。。这个框架的插件不好用。

**Comment by Socratea** [comment]
饿了么UI

________________________________

**Comment by anjia0532** [comment]
iview,iview-admin,mint-ui,element,ant-design,ant-design-pro

**Comment by piglingcn** [comment]
的确太垃圾了。。一个下拉选项清空的功能，文档都没写。

**Comment by anjia0532** [comment]
相比较来说，ant-design的文档是比较全的，其他的，基本都得参考一下源码

**Comment by toknT** [comment]
@piglingcn 因为国情 这个已经很不错了...

**Comment by dinghao1994** [comment]
已经很好了

**Comment by foreverly** [comment]
我他吗刚开始就凉了吗
