### ISSUE TITLE
模态窗口如果屏幕过小的话窗口会挪到下面

### ISSUE THREAD

**Issue by sucaiji** [CloudDeepTeam/amazeui#1015]
## 复现步奏

1.首先，下载官网的文件
2.随便选择一个demo
3.复制模态窗口的任一示例
4.打开浏览器
5.宽度拉到274以下
6.窗口不见了
...

**Comment by sucaiji** [comment]
![tim 20171230221840](https://user-images.githubusercontent.com/24414817/34454896-837b2f96-edaf-11e7-9f99-d4be57828cdf.png)

**Comment by chong0808** [comment]
这个不是移动端的吧 ？ 是不是要专门用移动端的组件？
