### ISSUE TITLE
 Amaze UI Gallery 图片画廊插件问题

### ISSUE THREAD

**Issue by bozomoyy** [CloudDeepTeam/amazeui#1019]
缩放的时候，被黑色区域被限制住了纵向的高度，图片是放大的，但是在页面中却没有撑开，如下两图，怎么办？
缩放前：
![image](https://user-images.githubusercontent.com/9572710/34717190-247345ae-f56d-11e7-8d31-19943beacd6f.png)
缩放后：
![image](https://user-images.githubusercontent.com/9572710/34717199-34eafb70-f56d-11e7-8734-8bd91ca8d9ec.png)

**Comment by lwxyfer** [comment]
需要更详细的信息。
