### ISSUE TITLE
Bug: JS插件-全屏切换功能

### ISSUE THREAD

**Issue by Jakeylove** [CloudDeepTeam/amazeui#1026]
**问题描述**

JS插件-全屏切换功能：使用浏览器快捷键（F11）打开全屏后，再点击全屏切换按钮无效。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：windows10
- 浏览器及版本：Google Chrome(62.0.3202.89)
- 演示地址：
http://amazeui.org/javascript/fullscreen
**复现步奏**
**UA:** 
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
```

**Comment by minwe** [comment]
Windows 上 Chrome 按 F11 会进入全屏吗？回头找一个试试。
