### ISSUE TITLE
Bug: 官网实例报错

### ISSUE THREAD

**Issue by haifeizhou** [CloudDeepTeam/amazeui#1031]
**问题描述**

（描述一下问题）

**产生环境**

- 操作系统及版本：window7 64位
- 浏览器及版本：谷歌、360
- 演示地址：http://amazeui.org/javascript

**复现步奏**

1. 控制台报错导致实例无法预览

**Comment by minwe** [comment]
部分资源加载不到，估计是七牛云存储那边出问题了。

@lwxyfer 可以联系一下问问。

**Comment by minwe** [comment]
应该恢复了， @haifeizhou 强制刷新试试。

**Comment by haifeizhou** [comment]
嗯恢复了谢谢

**Comment by edisonnara** [comment]
>我昨天也发现了, 开始以为是官网组件失效了, 开了控制台才知道怎么回事
*难道是7牛欠费了, 或者7牛不想免费了*
