### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by wzcl** [CloudDeepTeam/amazeui#1034]
**问题描述**
css等分网格 九宫格 点击后 所有界面上的字消失 且网页卡死  
（描述一下问题）

**产生环境**
全部 
- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:**

**Comment by psc0606** [comment]
This project has already been deprecated, no body maintain.
