### ISSUE TITLE
如何点击一次重新设置限制视图模式

### ISSUE THREAD

**Issue by qwm876677344** [CloudDeepTeam/amazeui#1038]
## 问题描述

比如设置的试图是结束时间，为2018-05-10之后不能点击。
因为跨天，现在时间变成了2018-05-11，视图还是2018-05-10之后不能点击。

**Comment by minwe** [comment]
说的是日期选择插件？

没有更新参数的接口，不过你可以试一下点击以后修改插件实例的 `onRender` 选项：
 
```js
$('#my-end-2').data('amui.datepicker').options.onRender = function() {};
```
