### ISSUE TITLE
modal中tabs显示问题

### ISSUE THREAD

**Issue by canbingzt** [CloudDeepTeam/amazeui#1044]
## 问题描述

如果在modal中使用tabs，会有以下问题
用class="am-active"指定“激活”的tab会没有高度导致显示不出来，切换其他tab再切换回来会正常显示。
如果没有class="am-active"，则会默认显示第一个tab，此时没有显示问题。

## 产生环境

- **操作系统及版本：win10（在系统设置关于里面可以查看）
- **浏览器及版本：Chrome 66（一般在浏览器「帮助」或者「关于」里面）

**Comment by git-zhaidy** [comment]
这个问题解决了么？怎么没人回复啊，没人遇到过么？
