### ISSUE TITLE
单张图片点击会有一个黑色遮罩，关闭了就ok了~

### ISSUE THREAD

**Issue by QAwangyang** [CloudDeepTeam/amazeui#1049]
点击网站里的图片，会出现一个遮罩在最上层，关掉后才能正常显示
http://blog.jcgame.net/blog/cocos_performance.html   可以在这个页面看看

**Comment by minwe** [comment]
引了两份  amazeui.min.js
<http://blog.jcgame.net/static/assets/js/amazeui.min.js>，去掉一个
