### ISSUE TITLE
js插件 tab页动态添加标签页无法使用

### ISSUE THREAD

**Issue by 151608133** [CloudDeepTeam/amazeui#1054]
我讲js插件模板的示例代码取下来，本地无法使用，写死的tab页可以切换，但是动态添加的切不动，调试发现tab页标签上动态添加的没有加上监听事件。
![default](https://user-images.githubusercontent.com/21124892/42610399-022d73ec-85c4-11e8-979f-1124fcdb5f89.png)

**Comment by zlunr** [comment]
# 不更新了！
