### ISSUE TITLE
大家别用这个框架了，一堆坑

### ISSUE THREAD

**Issue by psc0606** [CloudDeepTeam/amazeui#1056]
没人维护这个框架了，一堆坑，大家慎用哎~~

**Comment by 4133789** [comment]
感觉这个框架还是挺不错的 特别是布局和配色 现成的就挺好使
我还做了几个页面 感觉也还可以.
但是感觉深入使用的话 毕竟已经不更新了
不过一般的功能感觉还好
不知道你说的坑都是哪些地方
希望可以列举一下 让后面的人看到.

现在不更新了 我也不敢接着用了....好生蛋疼.

**Comment by psc0606** [comment]
你说得很对，在中文版的UI框架中，还算比较漂亮的，我当初就是因为这个才使用的，不维护的东西就别用了，坑是在太多，你去官网上和那个论坛里看，一堆问题，但是没人回复。我现在使用折叠列表折叠时失效，模态框弹出式，如果带滚动条就有明显的效果影响等等。。。。

**Comment by yanue** [comment]
人家去套壳去了  哪有时间更新这个

**Comment by shanjixiaboss** [comment]
这个不赚钱，没政府项目好坑，关键是你官网demo都报错了，我随手就给你。。。。。。把页面关了

**Comment by foreverly** [comment]
我去，还好我是个人博客，刚用没两天发现好多BUG，select和botton控件都有问题，暂时自己解决了，妈蛋，现在已经没人更新了吗？
