### ISSUE TITLE
初学者问一下，如何在angular使用amazeui

### ISSUE THREAD

**Issue by makyo5** [CloudDeepTeam/amazeui#1058]
您好，我算是angular的初级使用者，能够做一些普通网页。但是对样式不是很熟练。
我知道如何在angular中自己写样式，然后使用。
但是，我不知道如何在angular使用amazeui样式。
我下载了amazeui包。
放在node_modules中。
并且在angular.json的styles, scripts中，添加了相关css和js的路径。
但是，npm start会失败，或者卡在95%的地方。
请问一下，有相关教程吗。感谢。

**Comment by minwe** [comment]
https://blog.csdn.net/qq_34645412/article/details/77148132

参考一下这个文档
