### ISSUE TITLE
演示站cdn失效？

### ISSUE THREAD

**Issue by 5am3** [CloudDeepTeam/amazeui#1077]
## 问题描述
在查看文档时，发现多处jquery调用失败。
无法正常调用js
http://cdn.amazeui.org/jquery/2.1.4/jquery.min.js

## 产生环境

- **设备及型号：** MacBook
- **操作系统及版本：**  macos
- **浏览器及版本：** Chrome
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：** 
![20181017153975967469238.png](http://img.5am3.com/20181017153975967469238.png)
  

## 复现步奏

1. http://amazeui.github.io/masonry/docs/panel.html
2. 查看console

**Comment by shihbas** [comment]
我刚看了下  现在没有问题了吧
![image](https://user-images.githubusercontent.com/43459110/47712691-50380b00-dc73-11e8-9dfd-5860958e3612.png)
