### ISSUE TITLE
BUG：全屏报错

### ISSUE THREAD

**Issue by cnbase** [CloudDeepTeam/amazeui#1089]
## 问题描述

官方实例，全屏报错。

## 产生环境

- **设备及型号：PC
- **操作系统及版本：win10 1809
- **浏览器及版本：chrome 71
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**

![tim 20190114181009](https://user-images.githubusercontent.com/30611253/51107053-ace5a380-1828-11e9-861c-a3e9e656c10f.png)

**Comment by kisaragychihaya** [comment]
把15584行那儿的`elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);`
改成
```
if (keyboardAllowed) {
                                elem[request](Element.ALLOW_KEYBOARD_INPUT);
                            } else {
                                elem[request]({navigationUI: "auto"});
                            }
```
暂时解决了问题
