### ISSUE TITLE
AmazeUi首页CSS加载不出

### ISSUE THREAD

**Issue by yimchengjie** [CloudDeepTeam/amazeui#1105]
## AmazeUi首页CSS加载不出啊

（AmazeUi首页CSS加载不出）

## 产生环境

- **电脑：**普通笔记本电脑
- **操作系统及版本：**（windows10 教育版）
- **浏览器及版本：**Google Chrome 73.0.3683.103
- **问题截图/录屏：
![K{Q7}Q7%7C V2}VRA@GT0MV](https://user-images.githubusercontent.com/43691246/60225375-1dedb480-98b9-11e9-80b8-7f7655b9a364.png)

## 复现步奏

1.
![K{Q7}Q7%7C V2}VRA@GT0MV](https://user-images.githubusercontent.com/43691246/60225347-f7c81480-98b8-11e9-9161-315f88f5138b.png)

**Comment by milkmeowo** [comment]
@yimchengjie 估计早就弃坑了，CDN都挂了。不再维护了

**Comment by zhzh-zodiac** [comment]
过来看一下，不是我一个人

**Comment by ltp1024** [comment]
怎么办？

**Comment by yimchengjie** [comment]
现在好像好了?!

**Comment by 18070952318** [comment]
现在直接挂了

**Comment by oailgnos** [comment]
旧版文档哪里找？

**Comment by yimchengjie** [comment]
是的..今天直接挂了

**Comment by minwe** [comment]
各位还在使用 AmazeUI 的都是什么场景？
