### ISSUE TITLE
妹子GG了？

### ISSUE THREAD

**Issue by ltp1024** [CloudDeepTeam/amazeui#1106]
## 问题描述
妹子要挂掉了吗，网站怎么回事，没有下离线文档，难受啊
（简明扼要地描述一下问题）

## 产生环境

- **设备及型号：**（手机、平板等移动设备时填写此项，如 `iPhone 6s Plus`）
- **操作系统及版本：**（在系统设置关于里面可以查看）
- **浏览器及版本：**（一般在浏览器「帮助」或者「关于」里面）
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**

  （截图和录屏有助于我们更直观的理解你想表达的问题。如果需要，你可以使用 [LICEcap](http://www.cockos.com/licecap/) 录制 GIF 动画）

## 复现步奏

1.
2.
...

**Comment by simonkimi** [comment]
换官网了, 新官网:http://beta.amazeui.org/

**Comment by chadwicklee** [comment]
那个也是旧的，以前的3.0demo

**Comment by Windelight** [comment]
> 换官网了, 新官网:http://beta.amazeui.org/

已挂
