### ISSUE TITLE
网站无法正常访问

### ISSUE THREAD

**Issue by londy-hs** [CloudDeepTeam/amazeui#1110]
为什么官网无法访问了？想问下项目不干了？解散了？至少有一个说法吧，这不明不白的，给我支持者一个说法

**Comment by ATQQ** [comment]
我今天才看见,还好手里下载了离线文档

**Comment by luorunqi** [comment]
153538416@qq.com 求离线文档~~

**Comment by zwllxs** [comment]
求离线文档啊，求好人。
感谢感谢





------------------ 原始邮件 ------------------
发件人: "sugar"<notifications@github.com>;
发送时间: 2019年6月29日(星期六) 晚上9:55
收件人: "amazeui/amazeui"<amazeui@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [amazeui/amazeui] 网站无法正常访问 (#1110)




我今天才看见,还好手里下载了离线文档

**Comment by ATQQ** [comment]
离线文档地址:[百度网盘](https://pan.baidu.com/s/1lE6ZDftxbKjn473XVgQd3Q)
提取码 :**hkbi**
```text
链接：https://pan.baidu.com/s/1lE6ZDftxbKjn473XVgQd3Q 
提取码：hkbi 
复制这段内容后打开百度网盘手机App，操作更方便哦
```
