### ISSUE TITLE
有3.0.0beta版的镜像吗？

### ISSUE THREAD

**Issue by cafe0430** [CloudDeepTeam/amazeui#1114]
现在是什么情况。。

**Comment by AB901** [comment]
我也在找镜像 3.0 的

**Comment by AB901** [comment]
> 现在是什么情况。。

老哥你找到3.0镜像了吗

**Comment by cafe0430** [comment]
> > 现在是什么情况。。
> 
> 老哥你找到3.0镜像了吗
用网络时光机，得翻墙。

https://web.archive.org/web/20180603164543/http://beta.amazeui.org/www/components/normalize.html
