### ISSUE TITLE
Bug: 官网演示图标看不到效果

### ISSUE THREAD

**Issue by ayurep** [CloudDeepTeam/amazeui#1119]
**问题描述**
官网演示图标看不到效果
https://amazeui.clouddeep.cn/css/icon/
全部图标呈现出来的都是  口口口口口口口口口口口口口口口

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
```

**Comment by cafe0430** [comment]
CSS里链接的字体文件没加HTTPS，浏览器自动过滤掉不安全元素了。解决办法是把网址http://amazeui.clouddeep.cn/css/icon/里的https改成http就可以显示了。
同志们人总要长大**当断则断**！！
