### ISSUE TITLE
网站是不是挂掉了？

### ISSUE THREAD

**Issue by vodka0629** [CloudDeepTeam/amazeui#1140]
似乎主页和 2.x 版本的都在提示错误，比如：
- https://amazeui.clouddeep.cn/

1.x 版本的还勉强可用，比如：
- https://amazeui.clouddeep.cn/1.x/css/

SSL 证书也过期了，真的很令人担心

**Comment by lizhiding** [comment]
貌似没人维护

**Comment by JackieLieu** [comment]
官网文档 可以访问这个地址 http://amazeui.wanjiaxinrc.com 查看

**Comment by prayjourney** [comment]
同502

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！
