### ISSUE TITLE
Bug: amazeui.ie8polyfill.min.js 找不到了

### ISSUE THREAD

**Issue by yfgcq** [CloudDeepTeam/amazeui#1162]
**问题描述**
http://cdn.amazeui.org/amazeui/2.7.0/js/amazeui.ie8polyfill.min.js
这个js组件找不到了，在哪里下载勒？

**Comment by minwe** [comment]
https://github.com/amazeui/amazeui/releases/tag/v2.7.2

下载 Source code 解压以后 `dist` 目录里有。

话说现在还需要关注 IE8 吗
