### ISSUE TITLE
JS: Collapse 折叠内容动画处理改进

### ISSUE THREAD

**Issue by minwe** [CloudDeepTeam/amazeui#223]
由于 jQuery 对高度计算比较奇葩的处理方式（忽略 `box-sizing`），Collapse 折叠内容的容器不能加上垂直的 `margin`、`padding`、`border`，否则高度计算会有问题导致动画效果会有顿涩感。

目前通过 #221 解决了展开时的问题，但闭合的时候仍然会有问题，需要抽空再处理一下，以解除上面的限制。

**Comment by ZhengGuang** [comment]
示例页面中移动端 .am-topbar-collapse 设置了 padding 导致了上述问题。

**Comment by vicvinc** [comment]
请教一个设计上的问题，如果折叠部分是折叠内容区域，内容在可视区上方的时候，收缩折叠区域会引起页面的塌缩，导致滚动，这样做有办法避免么？如果没有的话…这样的设计是否合理

**Comment by lwxyfer** [comment]
没有。合理。内容展开肯定是要占空间的。 
你要是有合理的建议，可以提出来看看能否进行改进。

**Comment by vicvinc** [comment]
@lwxyfer  后面的问题有点误会了，我这边接到一个设计，要使用伸缩折叠一部分文档内容，折叠按钮在文档的底部，所以用户阅读到最后再收起来的时候，页面会往下滚，所以我有点怀疑这样做是不是合适

**Comment by minwe** [comment]
不想触发页面滚动的话可以用 Modal 或者 Popover 之类的展现形式。

**Comment by vicvinc** [comment]
@minwe thx~
