### ISSUE TITLE
引入自动化测试工具

### ISSUE THREAD

**Issue by minwe** [CloudDeepTeam/amazeui#238]
自动化测试工具：
- https://saucelabs.com/
- http://www.browserstack.com/

测试框架：
- http://jasmine.github.io/2.1/introduction.html
- https://www.npmjs.com/package/karma-browserify
- https://github.com/TYRONEMICHAEL/react-component-boilerplate
- https://shcatula.wordpress.com/2014/02/16/karma-browserify/
- http://maketea.co.uk/2014/05/22/building-robust-web-apps-with-react-part-3.html
- https://github.com/amitayd/grunt-browserify-jasmine-node-example

**Comment by rocklau** [comment]
速度引领大家进入自动化世界吧.哈哈
