### ISSUE TITLE
2.0刷新页面字体变大，然后才恢复正常

### ISSUE THREAD

**Issue by looping84** [CloudDeepTeam/amazeui#371]
**问题描述**

2.0刷新页面字体变大，然后才恢复正常

**产生环境**
- 设备：
- 操作系统及版本： mac 10.9.5
- 浏览器及版本：chrome  Version 39.0.2171.95 (64-bit)
- 演示地址：

**复现步奏**
1. 直接 强制刷新，字体先变大，然后恢复正常

...

**Comment by Minwe** [comment]
以前在 iframe 里偶尔会看到这样的情形，但是现在已经无法重现了。‘
你是在官网上还是自己做的页面上遇到的？

**Comment by looping84** [comment]
@Minwe   在自己的页面上看到的，非常明显。。

**Comment by ww380459000** [comment]
![qq 20150607220954](https://cloud.githubusercontent.com/assets/2534696/8024344/a8be063c-0d62-11e5-9964-ba53978331a1.png)
![qq 20150607221158](https://cloud.githubusercontent.com/assets/2534696/8024341/a710d1fc-0d62-11e5-92e8-7fa7c05f8861.png)
![qq 20150607220944](https://cloud.githubusercontent.com/assets/2534696/8024342/a78350f6-0d62-11e5-8028-dab6343b0bee.png)

我也遇到这问题了，v2.3.0  win7 chrome

**Comment by lndj** [comment]
话说我之前没注意，我也常遇到

**Comment by wengyulin** [comment]
问下这种情况应该如何解决


来自 魅蓝

-------- 原始邮件 --------
发件人：Ning Luo <notifications@github.com>
时间：周日 6月7日 22:18
收件人：allmobilize/amazeui <amazeui@noreply.github.com>
主题：Re: [amazeui] 2.0刷新页面字体变大，然后才恢复正常 (#371)

**Comment by wengyulin** [comment]
问下这种情况应该如何解决


来自 魅蓝

-------- 原始邮件 --------
发件人：ww380459000 <notifications@github.com>
时间：周日 6月7日 22:17
收件人：allmobilize/amazeui <amazeui@noreply.github.com>
主题：Re: [amazeui] 2.0刷新页面字体变大，然后才恢复正常 (#371)

**Comment by xfworld** [comment]
我偶尔也会遇到这种情况...一把多刷两次就没了.... 不好重现

**Comment by minwe** [comment]
这应该是浏览器本身的问题，因为我在别的不使用 Amaze UI 的网站上有时也会出现这种现象。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://qastore.pl/principal.php?vn43>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://yyy.finansist24.ru/conversation.php?nvodc>

 

Again_moon@sohu.com
