### ISSUE TITLE
Menu、折叠面板、侧滑菜单等组件在部分安卓手机中性能问题收集

### ISSUE THREAD

**Issue by minwe** [CloudDeepTeam/amazeui#74]
via [@debug2012](http://weibo.com/wanghuan2011)

> 米2 ， chrome浏览器打开速度还能接受，但是微信浏览器菜单弹出延时至少2S。希望可以及时优化。

**Comment by Minwe** [comment]
#395  **魅族MX2浏览侧边栏菜单时崩溃**

> 问题描述
  魅族MX2浏览侧边栏菜单，打开后在关闭时崩溃。建议优化js
  IPhone4s没问题，UC浏览器没问题

>  产生环境

>  设备：魅族
  操作系统及版本：Android 4.0

**Comment by Stephenzxb** [comment]
移动设备上offcavas组件中存在input情况下，focus时由于输入法弹出会导致offcavas关闭。
桌面上，打开浏览器调试窗口，或改变浏览器窗口大小也会导致offcavas关闭。
貌似是窗口宽高改变时，都会出现这样的情况。
