### ISSUE TITLE
建议: 增加 Amaze UI 的 Axure 元件

### ISSUE THREAD

**Issue by fzhongj** [CloudDeepTeam/amazeui#907]
## 问题描述

请问有没有Amaze UI的Axure元件，这样可以方便PM直接使用Amaze UI的样式做原型图
## 产生环境
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：
## 复现步奏
1. 
2. 
   ...

**Comment by minwe** [comment]
目前没有，以后会对相关实现做评估。

**Comment by xfworld** [comment]
那还不如直接出个可以拖拽的编辑界面，能够保存为html，不更好么？ ：）
