### ISSUE TITLE
dropdown可以打开，但是无法收回

### ISSUE THREAD

**Issue by lixiang1991** [CloudDeepTeam/amazeui#935]
## 问题描述

我实现的功能是点击table的表头弹出dropdown，点击选项来进行筛选。
因此和官方示例的点击button弹出不一样。也不能按照button来做，实际上用span或者button都会导致这个bug。
问题表现为：点击span弹出包含多个li的ul。点击弹出它的span或者鼠标点到空白处，都不会关闭。只有点击li才能选择一个选项并关闭弹窗。
查看源码检查后我找到问题所在了。是出在animation上。
我把 Dropdown.prototype.close和Dropdown.prototype.open里的
```
//	  if (animation) {
//	    this.animating = 1;
//	      console.log("animating");
//	    $dropdown.addClass(this.options.animation).
//	      on(animation.end + '.open.dropdown.amui', $.proxy(function() {
//	        complete();
//	        $dropdown.removeClass(this.options.animation);
//	      }, this));
//	  } else {
	    complete();
//	  }
```
注释以后，dropdown功能就正常了，点击span或者其他任意空白处都能关闭dropdown了。
但是我还是不知道动画功能怎么关闭，如果有地方能设置关闭动画，就不用改源码了吧。
## 产生环境

- chrome浏览器
- amazeui版本2.7.0

**Comment by lwxyfer** [comment]
get
