### ISSUE TITLE
Bug: 在示例代码中，ScrollSpy 等 JS 组件不能使用

### ISSUE THREAD

**Issue by jacksonwj** [CloudDeepTeam/amazeui#944]
**问题描述**

在官方提供的示例代码的后台管理页面中（admin-index.html 等），由于设置了
```
html, body { height: 100%; overflow: hidden; }
```
上述 CSS 代码导致了所有涉及页面滚动侦听的 JS 插件（如：ScrollSpy等）都不能用了。

**产生环境**

- 设备：
- 操作系统及版本：Windows 7 Pro x64
- 浏览器及版本：Chrome 55、IE 11
- 演示地址：

**复现步奏**

1. 为按钮添加 ScrollSpy 等滚动侦测功能（data-am-scrollspy 或 通过 JS 方式）
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
```

**Comment by lwxyfer** [comment]
默认监听的是 window 上的滚动事件，下个版本会加上个配置节点选项。
