### ISSUE TITLE
官方定制框架的问题

### ISSUE THREAD

**Issue by jacksonwj** [CloudDeepTeam/amazeui#946]
使用妹子的 [定制框架](http://customize.amazeui.org)，生成出来的 css 文件中，不包含 **等分网格** `am-svg-……` 吗？

我的定制情况如下（是不是哪个组件漏选了，才导致没有生成 **等分网格** 的 css？）：

![](https://cloud.githubusercontent.com/assets/61455/22686294/8024a676-ed5e-11e6-8599-5f59d37f655a.png)

**Comment by lwxyfer** [comment]
十分感谢， 等分网格给漏了，这边比较忙，我后天给修复下。
