### ISSUE TITLE
$('myForm').validator('isFormValid') 验证报错

### ISSUE THREAD

**Issue by Yaecho** [CloudDeepTeam/amazeui#960]
## 问题描述

Form Validator
 $('myForm').validator('isFormValid') 验证radio报错

`<input type="radio" name="ResumeForm[sex]" value="男" data-am-ucheck required> 男`

input 的 name 中有[ ]会冲突
amazeui.js第15236行
` $field = this.$element.find('[name=' + $field.attr('name') + ']').first();`
修改为
` $field = this.$element.find('[name="' + $field.attr('name') + '"]').first();`
后正常。

**Comment by minwe** [comment]
当时没有考虑到 `name` 中包含 `[]` 的情形 👶

**Comment by xfworld** [comment]
还有方括号.... 囧
