### ISSUE TITLE
请问这妹子框架还在维护么？

### ISSUE THREAD

**Issue by XavierShi** [CloudDeepTeam/amazeui#964]
请问这妹子框架还在维护么？ 2017-5-17
🐱

**Comment by jiaxunjiaxun** [comment]
维护啊~
[https://github.com/amazeui/amazeui/wiki/Roadmap](https://github.com/amazeui/amazeui/wiki/Roadmap)
注意更新时间~还是给开发团队多一些时间~

**Comment by xunjianxiang** [comment]
虽然有 roadmap, 但是仍然会有项目放弃维护的感觉。
v3 和 v4 没有时间轴，没有进度~~

**Comment by xfworld** [comment]
暂时没什么版本变动了，会维护bug吧.....目前的现状就是如此
