### ISSUE TITLE
下拉选项(Selected), js 操作select 无效

### ISSUE THREAD

**Issue by huagelong** [CloudDeepTeam/amazeui#971]
## 问题描述

下拉选项(Selected), js 操作select 无效

官方文档网址 http://amazeui.org/javascript/selected?test=b

点击 “交替 Orange 选中状态"按钮没有效果

浏览器是:chrome 58.0.3029.110 (64-bit)
系统是:macos
 Amaze UI v2.7.2

**Comment by xfworld** [comment]
<pre>
 if (!$.AMUI.support.mutationobserver) {
      $selected.trigger('changed.selected.amui');
    }
!$.AMUI.support.mutationobserver 这个function已经无法正常识别了，
 需要直接调用
 $selected.trigger('changed.selected.amui');
</pre>

希望能帮到你
