### ISSUE TITLE
单选下拉选项(Selected), js 第二次操作select 无效

### ISSUE THREAD

**Issue by ldybyz** [CloudDeepTeam/amazeui#973]
使用版本：Amaze UI v2.7.2

第一次用js操作，操作成功
 $('#md-addfile-filetype').find('option').eq(0).attr('selected', true);
 $('#md-addfile-filetype').trigger('changed.selected.amui');

用鼠标选择下拉框的其他选择选项后，再次操作，操作失败
 $('#md-addfile-filetype').find('option').eq(0).attr('selected', true);
 $('#md-addfile-filetype').trigger('changed.selected.amui');

无意中此时发现select标签竟然有两个option有selected="selected"属性，
把上面的代码换为如下，先去除select标签的select属性，操作成功
 $('#md-addfile-filetype').find('option').removeAttr("selected");
$('#md-addfile-filetype').find('option').eq(0).attr('selected', true);
$('#md-addfile-filetype').trigger('changed.selected.amui');

我以为这样就成功了但是问题居然还有，如下面代码，第一次操作可以选中第二选项，第二次操作居然是第一选项了，后面的也都是第一选项
 $('#md-addfile-filetype').find('option').removeAttr("selected");
$('#md-addfile-filetype').find('option').eq(1).attr('selected', true);
$('#md-addfile-filetype').trigger('changed.selected.amui');

ps:我不知道这算是不是一个bug，但是我的下拉框是在弹出框中，需要再次弹出把下拉框的值恢复到默认值，但是按照官方的文档操作存在问题。

**Comment by ldybyz** [comment]
最终解决方法：
$('#md-addfile-filetype').find('option').removeAttr("selected");
$('#md-addfile-filetype').val("这里为选中项的值");
$('#md-addfile-filetype').find('option').eq(1).attr('selected', true);
$('#md-addfile-filetype').trigger('changed.selected.amui');

ps:虽然解决了，但是还是不清楚原理

**Comment by xfworld** [comment]
建议先destory，然后重新初始化后，在给值；
实际上是由事件传递完成的数据变化，确实会有影响；不了解实际情况的人，用起来会觉得蹩手蹩脚的

**Comment by ldybyz** [comment]
@xfworld 谢谢建议~
