### ISSUE TITLE
往绑定了change时间的select添加选项会触发change

### ISSUE THREAD

**Issue by 13542202544** [CloudDeepTeam/amazeui#978]
代码如下:

    <select name="pid" data-am-selected="{maxHeight: 200}">
        <option value="0">顶级栏目</option>
        <option value="1">二级栏目</option>
    </select>
    <select id="asd" data-am-selected="{maxHeight: 200}">
        <option value="0">0目</option>
        <option value="1">1目</option>
    </select>
    <script>
    $(function() {
      $("[name='pid']").on('change', function() {
        console.log('change pid');
        $("#asd").append("<option value='2'>2目</option>");
      });
       $("#asd").on('change', function() {
        console.log('change  asd');
      });
    });
    </script>

当往第二个select中添加选项时候就会触发第二个select的change事件，怎么搞啊,我不想让他触发

**Comment by xfworld** [comment]
解除Change事件的绑定，添加完成后，在绑定Change事件

这个顺序好理解么？
