### ISSUE TITLE
select标签无效，点击之后无法弹出下拉框

### ISSUE THREAD

**Issue by zxkang** [CloudDeepTeam/amazeui#979]
## 问题描述

select标签无效，点击之后无法弹出下拉框
```html
<select data-am-selected="{searchBox: 1}">
  <option value="a">Apple</option>
  <option value="b">Banana</option>
  <option value="o">Orange</option>
  <option value="m">Mango</option>
  <option value="phone">iPhone</option>
  <option value="im">iMac</option>
  <option value="mbp">Macbook Pro</option>
</select>
```

## 产生环境

- **操作系统及版本：**（在系统设置关于里面可以查看）
Windows 7 (64bit)
- **浏览器及版本：**（一般在浏览器「帮助」或者「关于」里面）
Chrome 版本 58.0.3029.110 (64-bit)
- **Amaze UI版本**
Amaze UI v2.7.2
- **演示地址：**（请尽量提供可在线查看的演示地址）
- **问题截图/录屏：**
![image](https://user-images.githubusercontent.com/11555420/28147531-d7bcd7f8-67b3-11e7-8e03-9fa2fc2bc64a.png)

- **动态图**
![default](https://user-images.githubusercontent.com/11555420/28147696-e6a5c1c0-67b4-11e7-8043-b681a3edfdd3.gif)

**Comment by gyct** [comment]
通过js渲染的页面会有这个问题，直接加载的不会

**Comment by zxkang** [comment]
更新了最新版本的amaze.ui.css，问题解决了
