### ISSUE TITLE
官网针对modal模拟Confirm存在的问题处理方案三有问题

### ISSUE THREAD

**Issue by 8kaka8** [CloudDeepTeam/amazeui#981]
## 问题描述

官网针对modal模拟Confirm存在的问题处理方案三有问题

法三：Confirm 关闭后移除暂存的实例，再次调用时重新初始化；

$('#your-confirm').on('closed.modal.amui', function() {
  $(this).removeData('amui.modal');
});

经测试发现，使用此方法，移除暂存的实例，再次调用时重新初始化，会导致onConfirm/onCancel按钮多次绑定事件，使用on前未未使用off解除事件，多次调用modal会执行多次绑定的事件

**Comment by deepsea887** [comment]
谢谢

**Comment by Yihy** [comment]
同样遇到这样的问题了
