### ISSUE TITLE
定制站点定制不了 http://customize.amazeui.org/

### ISSUE THREAD

**Issue by devaping** [CloudDeepTeam/amazeui#982]
## 产生环境

 chrome浏览器

## 复现步奏

1.勾选组件和配置之后点击启动定制，按钮显示失败，请重试字眼
2.查看chrome控制台发现报如下错误：
XMLHttpRequest cannot load http://api.amazeui.org/customize. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://customize.amazeui.org' is therefore not allowed access. The response had HTTP status code 502.

**Comment by lwxyfer** [comment]
建议 Clone 到本地，手动修改文件，再构建即可。
